import type { PlayerAppearance } from './player-profiles';

/**
 * Women's draw snapshot for Madrid P1, 5 September 2026.
 * Pairings and profile evidence: WOMEN-ROSTER.md.
 */
export const WOMEN_TEAMS = [
  {
    name: 'Triay / Brea',
    players: ['Gemma Triay', 'Delfi Brea'],
    countries: 'ESP / ARG',
    style: 'Control y agresividad',
    color: '#e7a5b4',
  },
  {
    name: 'Josemaría / González',
    players: ['Paula Josemaría', 'Bea González'],
    countries: 'ESP / ESP',
    style: 'Potencia y velocidad',
    color: '#c4e86b',
  },
  {
    name: 'Sánchez / Ustero',
    players: ['Ari Sánchez', 'Andrea Ustero'],
    countries: 'ESP / ESP',
    style: 'Creatividad y anticipación',
    color: '#8fd8cf',
  },
  {
    name: 'Fernández / Calvo',
    players: ['Claudia Fernández', 'Martina Calvo'],
    countries: 'ESP / ESP',
    style: 'Lectura y transiciones',
    color: '#79b9df',
  },
];

/**
 * Stylized game models. Colors describe a recognizable 2026 palette, not replicas.
 * Sponsors stay empty because current photos do not prove a stable print layout.
 */
export const WOMEN_PROFILES: Record<string, PlayerAppearance> = {
  'gemma-triay': {
    id: 'gemma-triay',
    name: 'Gemma Triay',
    surname: 'TRIAY',
    height: 1.73,
    handedness: 'right',
    playingSide: 'left',
    build: 'athletic',
    gender: 'female',
    skin: '#c79072',
    hair: '#4b3328',
    hairStyle: 'ponytail',
    beard: 'none',
    kit: {
      shirt: '#9f5869',
      shorts: '#3b2531',
      accent: '#e7b7c1',
      ink: '#ffffff',
      brand: 'BULLPADEL',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'skirt',
    },
    racket: {
      color: '#342c31',
      accent: '#c69a62',
      brand: 'BULLPADEL',
      shape: 'teardrop',
    },
  },
  'delfi-brea': {
    id: 'delfi-brea',
    name: 'Delfi Brea',
    surname: 'BREA',
    height: 1.7,
    handedness: 'right',
    playingSide: 'right',
    build: 'athletic',
    gender: 'female',
    skin: '#c58b69',
    hair: '#523525',
    hairStyle: 'ponytail',
    beard: 'none',
    kit: {
      shirt: '#2c7669',
      shorts: '#142b31',
      accent: '#8ed2bc',
      ink: '#ffffff',
      brand: 'BULLPADEL',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'skirt',
    },
    racket: {
      color: '#1e2529',
      accent: '#75b6d2',
      brand: 'BULLPADEL',
      shape: 'diamond',
    },
  },
  'paula-josemaria': {
    id: 'paula-josemaria',
    name: 'Paula Josemaría',
    surname: 'JOSEMARÍA',
    height: 1.6,
    handedness: 'left',
    playingSide: 'right',
    build: 'compact',
    gender: 'female',
    skin: '#c98d6b',
    hair: '#3f291e',
    hairStyle: 'bun',
    beard: 'none',
    kit: {
      shirt: '#f0efe8',
      shorts: '#171a1d',
      accent: '#b8dc55',
      ink: '#20262a',
      brand: 'HEAD',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'skirt',
    },
    racket: {
      color: '#202428',
      accent: '#b8dc55',
      brand: 'HEAD',
      shape: 'diamond',
    },
  },
  'bea-gonzalez': {
    id: 'bea-gonzalez',
    name: 'Bea González',
    surname: 'GONZÁLEZ',
    height: 1.74,
    handedness: 'right',
    playingSide: 'left',
    build: 'athletic',
    gender: 'female',
    skin: '#c99575',
    hair: '#4a3024',
    hairStyle: 'ponytail',
    beard: 'none',
    kit: {
      shirt: '#6d3f62',
      shorts: '#2b2030',
      accent: '#c49ac0',
      ink: '#ffffff',
      brand: 'BULLPADEL',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeves',
      bottom: 'shorts',
    },
    racket: {
      color: '#20252a',
      accent: '#b6e1d6',
      brand: 'BULLPADEL',
      shape: 'diamond',
    },
  },
  'ari-sanchez': {
    id: 'ari-sanchez',
    name: 'Ari Sánchez',
    surname: 'SÁNCHEZ',
    height: 1.65,
    handedness: 'right',
    playingSide: 'left',
    build: 'compact',
    gender: 'female',
    skin: '#c58d6e',
    hair: '#473126',
    hairStyle: 'bun',
    beard: 'none',
    kit: {
      shirt: '#eee9df',
      shorts: '#20262c',
      accent: '#ef8e52',
      ink: '#23282c',
      brand: 'adidas',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'skirt',
    },
    racket: {
      color: '#23262a',
      accent: '#ef8e52',
      brand: 'adidas',
      shape: 'teardrop',
    },
  },
  'andrea-ustero': {
    id: 'andrea-ustero',
    name: 'Andrea Ustero',
    surname: 'USTERO',
    height: 1.7,
    handedness: 'left',
    playingSide: 'right',
    build: 'athletic',
    gender: 'female',
    skin: '#c98f70',
    hair: '#3a2923',
    hairStyle: 'ponytail',
    beard: 'none',
    kit: {
      shirt: '#cfe67a',
      shorts: '#eef1e8',
      accent: '#92d5c2',
      ink: '#263038',
      brand: 'HEAD',
      sponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'shorts',
    },
    racket: {
      color: '#eceee8',
      accent: '#8bcdbd',
      brand: 'HEAD',
      shape: 'round',
    },
  },
  'claudia-fernandez': {
    id: 'claudia-fernandez',
    name: 'Claudia Fernández',
    surname: 'FERNÁNDEZ',
    height: 1.64,
    handedness: 'right',
    playingSide: 'right',
    build: 'compact',
    gender: 'female',
    skin: '#c58d6c',
    hair: '#3a2922',
    hairStyle: 'braid',
    beard: 'none',
    kit: {
      shirt: '#172f4d',
      shorts: '#132137',
      accent: '#73a9c7',
      ink: '#ffffff',
      brand: 'BULLPADEL',
      sponsor: 'ALPINE',
      backSponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'shorts',
    },
    racket: {
      color: '#5a3d36',
      accent: '#e7d7bd',
      brand: 'BULLPADEL',
      shape: 'teardrop',
    },
  },
  'martina-calvo': {
    id: 'martina-calvo',
    name: 'Martina Calvo',
    surname: 'CALVO',
    height: 1.66,
    handedness: 'right',
    playingSide: 'left',
    build: 'compact',
    gender: 'female',
    skin: '#ca9272',
    hair: '#382720',
    hairStyle: 'ponytail',
    beard: 'none',
    kit: {
      shirt: '#173349',
      shorts: '#173349',
      accent: '#67b4cc',
      ink: '#ffffff',
      brand: 'OYSHO',
      sponsor: 'CUPRA',
      backSponsor: '',
      pattern: 'plain',
      cut: 'sleeveless',
      bottom: 'skirt',
    },
    racket: {
      color: '#20252a',
      accent: '#72c2dd',
      brand: 'BABOLAT',
      shape: 'teardrop',
    },
  },
};
